name: deploy_site

on:
  - push
  - workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout comtext_builder repo
        uses: actions/checkout@v4
        with:
          repository: comtextspace/comtext_builder
          path: builder

      - name: Cache pandoc binary
        id: cache-pandoc
        uses: actions/cache@v4
        with:
          path: pandoc
          key: pandoc-3.7.0.2-${{ runner.os }}
          
      - name: Download pandoc
        if: steps.cache-pandoc.outputs.cache-hit != 'true'
        run: |
          mkdir -p pandoc
          wget -q https://github.com/jgm/pandoc/releases/download/3.7.0.2/pandoc-3.7.0.2-linux-amd64.tar.gz -O pandoc.tar.gz
          tar -xzf pandoc.tar.gz -C pandoc --strip-components=1
          rm pandoc.tar.gz
          
      - name: Add pandoc to PATH
        run: |
          sudo ln -s $PWD/pandoc/bin/pandoc /usr/local/bin/pandoc
          
      - name: Check pandoc version
        run: pandoc --version

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            builder/node_modules
            /home/runner/.cache/yarn/v6
          key: ${{ runner.os }}-yarn-builder-${{ hashFiles('builder/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-builder-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: builder
        run: yarn --frozen-lockfile

      - name: Build pages
        working-directory: builder
        run: node ./index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # run build script
      - name: Build VuePress site
        working-directory: builder
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: builder/docs/.vuepress/dist
          fqdn: rubin.comtext.space
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
