name: deploy_site

on:
  - push
  - workflow_dispatch

jobs:
  call-deploy:
    uses: comtextspace/comtext-builder-workflow/.github/workflows/deploy-01.yml@main
    with:
      url: rubin.comtext.space